PRO_STRIPE_ID = 'pro'
STARTER_STRIPE_ID = 'starter'

DEFAULT_TRIAL_DAYS = 30

CHARGE_FOR_OWNER = 19
CHARGE_FOR_OTHER_USERS = 12
STRIPE_CURRENCY = 'usd'
STRIPE_INTERVAL = 'month'
STRIPE_SETTLEMENT_DESCRIPTION = 'Charge for final settlement'
